name: CD - Deploy to EC2

on:
  workflow_run:
    workflows: ["CI Build and push Image"]  
    types: [completed]
    branches: [feature/ec2-infra-deploy, main]


env:
  AWS_REGION: us-east-1 

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Chechout
      uses: actions/checkout@v4

    - name: Setup AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: us-east-1
