name: CI Build and push Image 

on:
  pull_request:
      branches: [main]

env:
    AWS_REGION: us-east-1        

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get code
      uses: actions/checkout@v4

    - name: Setup AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
       
    - name: get  my AWS account number 
      run: |
        MY_ACCOUNT=$(aws sts get-caller-identity --query Account --output text)
        echo "My account is: $MY_ACCOUNT"
        echo "MY_ACCOUNT=$MY_ACCOUNT" >> $GITHUB_ENV
    
    - name: create image storage 
      run: |
        echo "creating ECR repositories ... "
        aws ecr create-repository --repository-name my-frontend 2>/dev/null && echo "frontend repo created" || echo "frontend repo exist"
        aws ecr create-repository --repository-name my-backend 2>/dev/null && echo "backend repo created"|| echo "backend repo exist"

    - name: login to ECR
      run: |
        echo "Logging into ECR ..."
        aws ecr get-login-password | docker login --username AWS --password-stdin $MY_ACCOUNT.dkr.ecr.us-east-1.amazonaws.com 
        echo "ECR Login successful"     

    - name: Build and push frontend image
      run: |
        echo "Building frontend Docker image..."
        docker build -t $MY_ACCOUNT.dkr.ecr.us-east-1.amazonaws.com/my-frontend:latest ./frontend
        docker push $MY_ACCOUNT.dkr.ecr.us-east-1.amazonaws.com/my-frontend:latest
        echo " Frontend image pushed to ECR"

    - name: Build and push backend image
      run: |
        echo "Building backend Docker image..."
        docker build -t $MY_ACCOUNT.dkr.ecr.us-east-1.amazonaws.com/my-backend:latest ./backend
        docker push $MY_ACCOUNT.dkr.ecr.us-east-1.amazonaws.com/my-backend:latest
        echo " Backend image pushed to ECR"