name: CI Build and push Image 

on:
    push:
        branches: [feature/ec2-infra-deploy, main]
    pull_request:
        branches: [main]

env:
    AWS_REGION: us-east-1        

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get code
      uses: actions/checkout@v4

    - name: Setup AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
       
    - name: get  my AWS account number 
      run: |
        MY_ACCOUNT=$(aws sts get-caller-identity --query Account --output text)
        echo "My account is: $MY_ACCOUNT"
        echo "MY_ACCOUNT=$MY_ACCOUNT" >> $GITHUB_ENV
    
    - name: create image storage 
      run: |
        aws ecr create-repository --repository-name my-frontend || echo "Already exist"
        aws ecr create-repository --repository-name my-backend || echo "Already exist"
