name: Build, Scan, Push to ECR and Deploy to EC2

on:
  push:
    branches: [main , ngrigoryan/learning ]

env:
  AWS_REGION: us-east-1
  ECR_REPO_FRONTEND: 650252169452.dkr.ecr.us-east-1.amazonaws.com/webapp/frontend
  ECR_REPO_BACKEND: 650252169452.dkr.ecr.us-east-1.amazonaws.com/webapp/backend
  DOCKER_BUILDKIT: 1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | \
            docker login --username AWS --password-stdin $ECR_REPO_FRONTEND

      - name: Build frontend Docker image
        run: docker build -t $ECR_REPO_FRONTEND ./frontend

      - name: Scan frontend with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.ECR_REPO_FRONTEND }}:latest

      - name: Push frontend to ECR
        run: docker push $ECR_REPO_FRONTEND:latest

      - name: Build backend Docker image
        run: docker build -t $ECR_REPO_BACKEND ./backend

      - name: Scan backend with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.ECR_REPO_BACKEND }}:latest

      - name: Push backend to ECR
        run: docker push $ECR_REPO_BACKEND:latest

  provision-ec2:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform apply -auto-approve

  deploy-on-ec2:
    needs: provision-ec2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i inventory.ini deploy-app.yml
